# Evento (b): Commits en main (después del merge)
name: Commit Checks y Docker Release

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  main_ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar pruebas unitarias en main
        run: pytest tests/test_app.py

      - name: Login a GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build -t ghcr.io/${{ github.repository }}/diagnostico-medico:latest .

      - name: Publicar imagen en GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/diagnostico-medico:latest