# Evento (a): Pull Requests hacia main
name: PR Checks

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  pr_ci_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Comentar inicio de CI/CD
        uses: mshick/add-pr-comment@v2
        with:
          message: "CI/CD en acción. Ejecutando tareas …"

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar pruebas unitarias
        run: pytest tests/test_app.py

      - name: Comentar fin de CI/CD
        if: success()
        uses: mshick/add-pr-comment@v2
        with:
          message: "CI/CD terminado con éxito."
